[auth] add auth service
IndustryEssentials/ymir pull request #1628
Opened 2023-03-14 06:25 UTC by IJtLJZ8Rm4Yr

2023-03-14 06:46 UTC, phoenix-xhuang requested changes

2023-03-14 06:46 UTC, phoenix-xhuang commented on ymir/backend/src/ymir_auth/auth/api/api_v1/endpoints/login.py
> +    FailedToSendEmail,
现在这样的设计，有些地方不太清楚：
1，所有的constants要复制一份吗？比如像Errors、数据类之类，以后需要修改了怎么处理？
2，与原backend的数据格式、代码怎么共享？比如，app里面的user/role表、数据、代码准备怎么处理？
3，以后要加上的二次开发接口服务放哪里，也是像auth类似的方式吗？

2023-03-14 06:56 UTC, IJtLJZ8Rm4Yr commented on ymir/backend/src/ymir_auth/auth/api/api_v1/endpoints/login.py
> +    FailedToSendEmail,
3. 不是你要求放到 backend 这里的吗？

2023-03-14 07:24 UTC, phoenix-xhuang commented on ymir/backend/src/ymir_auth/auth/api/api_v1/endpoints/login.py
> +    FailedToSendEmail,
对，是要放到backend，所以是要确认具体的计划，比如是会有一个新的"supervisor/conf.d/ymir_cus_dev.ini"，还是放在现在的ymir_auth.ini。如果是放在ymir_auth.ini，那这个文件的名字就要考虑更改

2023-03-15 13:16 UTC, phoenix-xhuang commented on ymir/backend/src/ymir_auth/auth/main.py
> +import logging
auth和二次开发平台是对外的，与app面对内部web调用不一样，审计功能需要加上

2023-03-15 13:17 UTC, phoenix-xhuang commented on ymir/gateway/traefik.yml
> +entryPoints:
加上throttler

2023-03-15 13:19 UTC, phoenix-xhuang commented on ymir/backend/src/ymir_auth/auth/config.py
> +import secrets
这里的内容需要删减

2023-03-16 02:32 UTC, IJtLJZ8Rm4Yr commented on ymir/gateway/traefik.yml
> +entryPoints:
updated

2023-03-16 02:32 UTC, IJtLJZ8Rm4Yr commented on ymir/backend/src/ymir_auth/auth/config.py
> +import secrets
updated

2023-03-16 02:45 UTC, phoenix-xhuang submitted a review, later dismissed

2023-03-16 03:11 UTC, fenrir-z approved these changes, later dismissed

2023-03-16 04:50 UTC, phoenix-xhuang approved these changes

2023-03-16 05:52 UTC, fenrir-z approved these changes

2023-03-16 05:53 UTC, merged